<?php

/**
 * Icon system configuration — Font Awesome (legacy) → Lucide mapping.
 *
 * Used by IconHelper (Phase 1+) and the audit script (npm run audit:icons).
 * Keys use the fa-* glyph name without style prefix (e.g. fa-trash, not fas fa-trash).
 */
return [

    /*
    | Default SVG attributes for Lucide icons rendered via IconHelper / crmIcon().
    */
    'defaults' => [
        'size' => 16,
        'stroke_width' => 2,
        'class' => 'lucide icon',
    ],

    /*
    | Loading / spinner tokens — render with spin animation (loader-2).
    */
    'spinners' => [
        'fa-spinner' => 'loader-2',
    ],

    /*
    | Brand icons — Lucide has no brand set. Strategy: inline SVG via IconHelper::brand().
    | See docs/ICON-MIGRATION.md § Brand icons.
    */
    'brands' => [
        'fa-google' => 'google',
    ],

    /*
    | Legacy Font Awesome glyph → Lucide icon name.
    | Run `npm run audit:icons` after edits; unmapped tokens appear in docs/ICON-AUDIT.md.
    */
    'legacy' => [
        // Navigation & actions
        'fa-arrow-left' => 'arrow-left',
        'fa-arrow-right' => 'arrow-right',
        'fa-arrow-up' => 'arrow-up',
        'fa-arrow-down' => 'arrow-down',
        'fa-arrow-down-from-bracket' => 'log-out',
        'fa-arrow-right-from-bracket' => 'log-out',
        'fa-arrows-alt-h' => 'move-horizontal',
        'fa-arrows-alt' => 'move',
        'fa-caret-down' => 'chevron-down',
        'fa-caret-up' => 'chevron-up',
        'fa-caret-left' => 'chevron-left',
        'fa-caret-right' => 'chevron-right',
        'fa-angle-left' => 'chevron-left',
        'fa-angle-right' => 'chevron-right',
        'fa-angle-down' => 'chevron-down',
        'fa-angle-up' => 'chevron-up',
        'fa-align-left' => 'align-left',
        'fa-align-center' => 'align-center',
        'fa-align-right' => 'align-right',
        'fa-exchange-alt' => 'arrow-left-right',
        'fa-file-text' => 'file-text',
        'fa-file-word' => 'file-text',
        'fa-envelope-open-text' => 'mail-open',
        'fa-plane-departure' => 'plane-takeoff',
        'fa-trophy' => 'trophy',
        'fa-bullseye' => 'target',
        'fa-child' => 'baby',
        'fa-folder-minus' => 'folder-minus',
        'fa-gavel' => 'gavel',
        'fa-money-bill' => 'banknote',
        'fa-user-edit' => 'user-pen',
        'fa-user-tag' => 'user-round',
        'fa-wallet' => 'wallet',
        'fa-mobile' => 'smartphone',
        'fa-mouse-pointer' => 'mouse-pointer',
        'fa-pen-fancy' => 'pen-line',
        'fa-pen-nib' => 'pen-tool',
        'fa-heartbeat' => 'heart-pulse',
        'fa-mobile-alt' => 'smartphone',
        'fa-address-card' => 'id-card',
        'fa-arrow' => 'arrow-right',
        'fa-sign-in-alt' => 'log-in',
        'fa-signature' => 'signature',
        'fa-thumb-tack' => 'pin',
        'fa-ticket' => 'ticket',
        'fa-user-slash' => 'user-x',
        'fa-calendar-check-o' => 'calendar-check',
        'fa-calendar-clock' => 'calendar-clock',
        'fa-chevron' => 'chevron-right',
        'fa-file-archive' => 'file-archive',
        'fa-file-code' => 'file-code',
        'fa-file-excel' => 'file-spreadsheet',
        'fa-file-plus' => 'file-plus',
        'fa-file-powerpoint' => 'file-chart-column',
        'fa-hand-paper' => 'hand',
        'fa-hand-point-left' => 'hand-helping',
        'fa-infinity' => 'infinity',
        'fa-medal' => 'medal',
        'fa-money-bill-wave' => 'banknote',
        'fa-question' => 'circle-question-mark',
        'fa-smile' => 'smile',
        'fa-stamp' => 'stamp',
        'fa-thumbs-up' => 'thumbs-up',
        'fa-traffic-light' => 'traffic-cone',
        'fa-unlock-alt' => 'lock-open',
        'fa-user-times' => 'user-x',
        'fa-vial' => 'test-tube',
        'fa-chevron-down' => 'chevron-down',
        'fa-chevron-up' => 'chevron-up',
        'fa-chevron-left' => 'chevron-left',
        'fa-chevron-right' => 'chevron-right',
        'fa-ellipsis-h' => 'ellipsis',
        'fa-ellipsis-v' => 'ellipsis-vertical',
        'fa-bars' => 'menu',
        'fa-times' => 'x',
        'fa-times-circle' => 'circle-x',
        'fa-plus' => 'plus',
        'fa-plus-circle' => 'circle-plus',
        'fa-minus' => 'minus',
        'fa-check' => 'check',
        'fa-check-circle' => 'circle-check',
        'fa-check-double' => 'check-check',
        'fa-save' => 'save',
        'fa-edit' => 'pencil',
        'fa-pen' => 'pencil',
        'fa-pencil-alt' => 'pencil',
        'fa-trash' => 'trash-2',
        'fa-trash-alt' => 'trash-2',
        'fa-redo' => 'rotate-cw',
        'fa-undo' => 'undo-2',
        'fa-sync' => 'refresh-cw',
        'fa-sync-alt' => 'refresh-cw',
        'fa-download' => 'download',
        'fa-upload' => 'upload',
        'fa-search' => 'search',
        'fa-filter' => 'filter',
        'fa-sort' => 'arrow-up-down',
        'fa-sort-up' => 'arrow-up',
        'fa-sort-down' => 'arrow-down',
        'fa-sort-alpha' => 'arrow-up-a-z',
        'fa-sort-amount' => 'arrow-up-wide-narrow',
        'fa-sort-numeric' => 'arrow-up-1-0',
        'fa-external-link-alt' => 'external-link',
        'fa-link' => 'link',
        'fa-unlink' => 'unlink',
        'fa-copy' => 'copy',
        'fa-clone' => 'copy',
        'fa-print' => 'printer',
        'fa-eye' => 'eye',
        'fa-eye-slash' => 'eye-off',
        'fa-lock' => 'lock',
        'fa-unlock' => 'lock-open',
        'fa-sign-out-alt' => 'log-out',
        'fa-cogs' => 'settings',
        'fa-cog' => 'settings',
        'fa-wrench' => 'wrench',

        // Users & people
        'fa-user' => 'user',
        'fa-users' => 'users',
        'fa-user-plus' => 'user-plus',
        'fa-user-check' => 'user-check',
        'fa-user-circle' => 'circle-user',
        'fa-user-tie' => 'user-round',
        'fa-user-friends' => 'users',
        'fa-user-shield' => 'shield-user',
        'fa-user-cog' => 'user-cog',
        'fa-users-cog' => 'users-round',
        'fa-id-card' => 'id-card',
        'fa-id-badge' => 'badge',

        // Communication
        'fa-envelope' => 'mail',
        'fa-envelope-open' => 'mail-open',
        'fa-paper-plane' => 'send',
        'fa-mail-bulk' => 'mails',
        'fa-inbox' => 'inbox',
        'fa-reply' => 'reply',
        'fa-reply-all' => 'reply-all',
        'fa-share' => 'share-2',
        'fa-at' => 'at-sign',
        'fa-phone' => 'phone',
        'fa-phone-alt' => 'phone',
        'fa-sms' => 'message-square-text',
        'fa-comment' => 'message-circle',
        'fa-comments' => 'messages-square',
        'fa-bell' => 'bell',
        'fa-bullhorn' => 'megaphone',

        // Files & documents
        'fa-file' => 'file',
        'fa-file-alt' => 'file-text',
        'fa-file-pdf' => 'file-text',
        'fa-file-image' => 'file-image',
        'fa-file-invoice' => 'file-text',
        'fa-file-invoice-dollar' => 'receipt',
        'fa-file-signature' => 'file-signature',
        'fa-file-contract' => 'file-text',
        'fa-file-upload' => 'file-up',
        'fa-file-download' => 'file-down',
        'fa-file-export' => 'file-output',
        'fa-file-import' => 'file-input',
        'fa-folder' => 'folder',
        'fa-folder-open' => 'folder-open',
        'fa-paperclip' => 'paperclip',
        'fa-clipboard' => 'clipboard',
        'fa-clipboard-check' => 'clipboard-check',
        'fa-clipboard-list' => 'clipboard-list',
        'fa-sticky-note' => 'sticky-note',
        'fa-book' => 'book',
        'fa-archive' => 'archive',

        // Business & finance
        'fa-briefcase' => 'briefcase',
        'fa-building' => 'building-2',
        'fa-receipt' => 'receipt',
        'fa-dollar-sign' => 'dollar-sign',
        'fa-chart-line' => 'chart-line',
        'fa-chart-bar' => 'chart-column',
        'fa-chart-pie' => 'chart-pie',
        'fa-percentage' => 'percent',
        'fa-calculator' => 'calculator',
        'fa-credit-card' => 'credit-card',
        'fa-hand-holding-usd' => 'hand-coins',

        // Calendar & time
        'fa-calendar' => 'calendar',
        'fa-calendar-alt' => 'calendar',
        'fa-calendar-check' => 'calendar-check',
        'fa-calendar-day' => 'calendar-days',
        'fa-calendar-days' => 'calendar-days',
        'fa-calendar-week' => 'calendar-range',
        'fa-calendar-plus' => 'calendar-plus',
        'fa-calendar-minus' => 'calendar-minus',
        'fa-calendar-times' => 'calendar-x',
        'fa-clock' => 'clock',
        'fa-clock-o' => 'clock',
        'fa-hourglass-half' => 'hourglass',
        'fa-history' => 'history',

        // Status & alerts
        'fa-info-circle' => 'info',
        'fa-exclamation-circle' => 'circle-alert',
        'fa-exclamation-triangle' => 'triangle-alert',
        'fa-question-circle' => 'circle-question-mark',
        'fa-ban' => 'ban',
        'fa-flag' => 'flag',
        'fa-star' => 'star',
        'fa-heart' => 'heart',
        'fa-circle' => 'circle',
        'fa-dot-circle' => 'circle-dot',

        // Travel & location
        'fa-globe' => 'globe',
        'fa-map-marker-alt' => 'map-pin',
        'fa-map-marked-alt' => 'map',
        'fa-plane' => 'plane',
        'fa-passport' => 'book-user',
        'fa-home' => 'house',
        'fa-city' => 'building',

        // Education & work
        'fa-graduation-cap' => 'graduation-cap',
        'fa-tasks' => 'list-todo',
        'fa-list' => 'list',
        'fa-list-alt' => 'list',
        'fa-list-ul' => 'list',
        'fa-columns' => 'columns-3',
        'fa-table' => 'table',
        'fa-th' => 'layout-grid',
        'fa-th-list' => 'list',

        // UI & misc
        'fa-tachometer-alt' => 'gauge',
        'fa-dashboard' => 'layout-dashboard',
        'fa-tag' => 'tag',
        'fa-tags' => 'tags',
        'fa-code' => 'code',
        'fa-bolt' => 'zap',
        'fa-route' => 'route',
        'fa-random' => 'shuffle',
        'fa-grip-vertical' => 'grip-vertical',
        'fa-grip-horizontal' => 'grip-horizontal',
        'fa-thumbtack' => 'pin',
        'fa-image' => 'image',
        'fa-spinner' => 'loader-2',
        'fa-circle-notch' => 'loader-circle',
        'fa-person-booth' => 'store',
        'fa-award' => 'award',
        'fa-certificate' => 'badge-check',
        'fa-shield-alt' => 'shield',
        'fa-key' => 'key',
        'fa-qrcode' => 'qr-code',
        'fa-barcode' => 'barcode',
        'fa-hashtag' => 'hash',
        'fa-language' => 'languages',
        'fa-magic' => 'wand-sparkles',
        'fa-robot' => 'bot',
        'fa-database' => 'database',
        'fa-server' => 'server',
        'fa-plug' => 'plug',
        'fa-cloud' => 'cloud',
        'fa-cloud-upload-alt' => 'cloud-upload',
        'fa-cloud-download-alt' => 'cloud-download',
        'fa-wifi' => 'wifi',
        'fa-signal' => 'signal',
        'fa-video' => 'video',
        'fa-camera' => 'camera',
        'fa-microphone' => 'mic',
        'fa-headset' => 'headset',
        'fa-palette' => 'palette',
        'fa-paint-brush' => 'paintbrush',
        'fa-tools' => 'wrench',
        'fa-hammer' => 'hammer',
        'fa-box' => 'box',
        'fa-boxes' => 'boxes',
        'fa-truck' => 'truck',
        'fa-shopping-cart' => 'shopping-cart',
        'fa-store' => 'store',
        'fa-warehouse' => 'warehouse',
        'fa-industry' => 'factory',
        'fa-sitemap' => 'network',
        'fa-project-diagram' => 'workflow',
        'fa-stream' => 'align-justify',
        'fa-layer-group' => 'layers',
        'fa-object-group' => 'group',
        'fa-expand' => 'expand',
        'fa-compress' => 'shrink',
        'fa-window-maximize' => 'maximize',
        'fa-window-minimize' => 'minimize',
        'fa-window-restore' => 'restore',
        'fa-toggle-on' => 'toggle-right',
        'fa-toggle-off' => 'toggle-left',
        'fa-power-off' => 'power',
        'fa-play' => 'play',
        'fa-pause' => 'pause',
        'fa-stop' => 'square',
        'fa-step-forward' => 'skip-forward',
        'fa-step-backward' => 'skip-back',
        'fa-fast-forward' => 'fast-forward',
        'fa-fast-backward' => 'rewind',
        'fa-volume-up' => 'volume-2',
        'fa-volume-mute' => 'volume-x',
        'fa-music' => 'music',
        'fa-film' => 'film',
        'fa-tv' => 'tv',
        'fa-gamepad' => 'gamepad-2',
        'fa-dice' => 'dice-5',
        'fa-puzzle-piece' => 'puzzle',
        'fa-cube' => 'box',
        'fa-cubes' => 'boxes',
        'fa-gem' => 'gem',
        'fa-leaf' => 'leaf',
        'fa-tree' => 'tree-pine',
        'fa-sun' => 'sun',
        'fa-moon' => 'moon',
        'fa-cloud-sun' => 'cloud-sun',
        'fa-cloud-rain' => 'cloud-rain',
        'fa-snowflake' => 'snowflake',
        'fa-fire' => 'flame',
        'fa-water' => 'droplet',
        'fa-battery-full' => 'battery-full',
        'fa-battery-half' => 'battery-medium',
        'fa-battery-empty' => 'battery-low',
    ],

];
